trigger:
- none
variables:
- group: 'todo-variables-kv'

stages:
  - stage: Build
    pool: br-agent
    jobs:
      - job: Build
        displayName: Build job

        steps:
        - script: |
            sudo apt update
            sudo apt upgrade -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update
            sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
            sudo systemctl status docker
          displayName: Install docker

        - script: |
              sudo docker build -f backend/Dockerfile -t backend:$(Build.SourceVersion) backend/
              sudo docker images
              sudo docker images backend:latest --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.CreatedAt}}"
          displayName: Build backend

  - stage: Release
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Release
        steps:
        - script: |
            sudo docker login -u $(DOCKERHUB-USER) -p $(DOCKERHUB-PASSWORD)
            sudo docker image tag backend:$(Build.SourceVersion) $(DOCKERHUB-USER)/todo-app-backend:latest
            sudo docker image tag backend:$(Build.SourceVersion) $(DOCKERHUB-USER)/todo-app-backend:$(Build.SourceVersion)
            sudo docker push --all-tags $(DOCKERHUB-USER)/todo-app-backend
        - checkout: self
          submodules: true
        - task: AzureStaticWebApp@0
          inputs:
              app_location: '/frontend' # App source code path relative to cwd
              output_location: '/dist' # Built app content directory relative to app_location - optional
              azure_static_web_apps_api_token: $(AZURE-STATIC-WEB-APPS-API-TOKEN)
          displayName: Deploy Azure Static Web App

          env:
            DOCKERHUB-PASSWORD: $(DOCKERHUB-PASSWORD)
            DOCKERHUB-USER: $(DOCKERHUB-USER)
            AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE-STATIC-WEB-APPS-API-TOKEN)
