trigger:
  - none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - prod

  - name: action
    displayName: Terraform Action
    type: string
    default: apply
    values:
      - apply
      - destroy

variables:
  - group: "todo-app-variables-kv"
  - group: "todo-app-${{parameters.environment}}-variables"

stages:
  - stage: Build
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: Build
        displayName: Build job
        steps:
          - script: |
              sudo docker build -f backend/Dockerfile -t backend:$(Build.SourceVersion) backend/
              sudo docker images
              sudo docker images backend:latest --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.CreatedAt}}"
              sudo docker login -u $(DOCKERHUB-USER) -p $(DOCKERHUB-PASSWORD)
              sudo docker image tag backend:$(Build.SourceVersion) $(DOCKERHUB-USER)/todo-app-backend:latest
              sudo docker image tag backend:$(Build.SourceVersion) $(DOCKERHUB-USER)/todo-app-backend:$(Build.SourceVersion)
              sudo docker push --all-tags $(DOCKERHUB-USER)/todo-app-backend
            displayName: Build and push backend image

          - task: UseNode@1
            inputs:
              version: "18.x"
            displayName: "Install Node.js"

          - script: |
              cd frontend
              npm install
            displayName: "Install dependencies"

          - script: |
              cd frontend
              echo "VITE_API_BASE_URL=$(VITE_API_BASE_URL)" > .env.production
              npm run build
            displayName: "Build React app with environment variable"

          - task: PublishPipelineArtifact@1
            displayName: Publish Frontend Artifact
            inputs:
              targetPath: "$(Build.SourcesDirectory)/frontend/dist"
              artifact: "frontend-dist"
              publishLocation: "pipeline"

  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: TerraformPlan
        displayName: Terraform Plan
        steps:
          - checkout: self

          - script: |
              TERRAFORM_VERSION="1.14.4"
              curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/terraform
            displayName: Install Terraform

          - task: AzureCLI@2
            name: CheckStoragePlans
            displayName: Check if plans exist in Storage Account
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                PLAN_COUNT=$(az storage blob list \
                  --account-name tfstatetodoapp \
                  --container-name plans \
                  --auth-mode login \
                  --query "length(@)" \
                  --prefix "${{ parameters.environment }}/"
                  -o tsv)

                echo "Found $PLAN_COUNT existing plan files in Storage Account."

                if [ "$PLAN_COUNT" -eq 0 ]; then
                  echo "No plans found in Storage Account."
                  echo "##vso[task.setvariable variable=storageHasPlans;isOutput=true]false"
                else
                  echo "Plans already exist in Storage Account."
                  echo "##vso[task.setvariable variable=storageHasPlans;isOutput=true]true"
                fi

          - task: AzureCLI@2
            displayName: Terraform Plan
            name: SetPlanFile
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                PLAN_DIR="$(Pipeline.Workspace)/tfplan/${{ parameters.environment }}"
                PLAN_FILE="$PLAN_DIR/tfplan-${{ parameters.environment }}-$(Build.BuildId)"

                echo "##vso[task.setvariable variable=PLAN_FILE;isOutput=true]$PLAN_FILE"

                mkdir -p "$PLAN_DIR"

                terraform init -reconfigure -backend-config=environments/${{ parameters.environment }}/${{ parameters.environment }}.tfbackend

                terraform plan -out="$PLAN_FILE"

                echo "Created plan:"
                ls -la "$PLAN_DIR"

                set +e
                if [ "${{ parameters.action }}" = "destroy" ]; then
                  echo "Creating DESTROY plan..."
                  terraform plan \
                    -destroy \
                    -out="$PLAN_FILE" \
                    -detailed-exitcode
                else
                  echo "Creating APPLY plan..."
                  terraform plan \
                    -out="$PLAN_FILE" \
                    -detailed-exitcode
                fi

                EXIT_CODE=$?
                terraform show $PLAN_FILE

                set -e

                if [ $EXIT_CODE -eq 1 ]; then
                  echo "Terraform plan failed."
                  exit 1
                elif [ $EXIT_CODE -eq 0 ]; then
                  echo "No infrastructure changes detected."
                  echo "##vso[task.setvariable variable=terraformHasChanges;isOutput=true]false"
                elif [ $EXIT_CODE -eq 2 ]; then
                  echo "Infrastructure changes detected."
                  echo "##vso[task.setvariable variable=terraformHasChanges;isOutput=true]true"
                fi

                echo "Created plan:"
                ls -la "$PLAN_DIR"
              workingDirectory: $(System.DefaultWorkingDirectory)/infra
            env:
              ARM_SUBSCRIPTION_ID: $(subscription_id)
              TF_VAR_environment: ${{ parameters.environment }}
              TF_VAR_administrator_login: $(POSTGRES_USER)
              TF_VAR_subscription_id: $(subscription_id)
              TF_VAR_dockerhub_username: $(DOCKERHUB-USER)
              TF_VAR_postgres_user: $(POSTGRES_USER)
              TF_VAR_postgres_port: $(POSTGRES_PORT)
              TF_VAR_postgres_db: $(POSTGRES_DB)

      - job: ManualApproval
        displayName: Manual Approval
        dependsOn:
          - TerraformPlan

        condition: and(
          succeeded(),
          eq('${{ parameters.environment }}', 'prod'),
          eq(dependencies.TerraformPlan.outputs['TerraformPlan.terraformHasChanges'], 'true'),
          eq(dependencies.TerraformPlan.outputs['CheckStoragePlans.storageHasPlans'], 'false')
          )

        pool: server

        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440
            inputs:
              instructions: |
                Terraform detected infrastructure changes for PROD.

                Verify:
                - terraform plan
                - resources
                - cost impact
                - security impact

                Approve only if changes are expected.

              notifyUsers: |
                radziszewski.aleksander@gmail.com
              onTimeout: reject

      - job: UploadPlanAndTerraformApply
        displayName: Upload and Apply Terraform Plan
        variables:
          PLAN_FILE: $[ dependencies.TerraformPlan.outputs['SetPlanFile.PLAN_FILE'] ]
        dependsOn:
          - TerraformPlan
          - ManualApproval
        condition: |
          or(
            eq('${{ parameters.environment }}', 'dev'),
            and(
              eq('${{ parameters.environment }}', 'prod'),
              eq(dependencies.ManualApproval.result, 'Succeeded')
            )
          )
        steps:
          - checkout: self

          - script: |
              TERRAFORM_VERSION="1.14.4"
              curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/terraform
            displayName: Install Terraform

          - task: AzureCLI@2
            displayName: Recreate Terraform Plan
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                mkdir -p "$(Pipeline.Workspace)/tfplan/${{ parameters.environment }}"

                terraform init

                terraform plan -out="$PLAN_FILE"

                ls -la "$(Pipeline.Workspace)/tfplan/${{ parameters.environment }}"
              workingDirectory: $(System.DefaultWorkingDirectory)/infra

          - task: AzureCLI@2
            displayName: Upload Terraform plan
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                az storage blob upload \
                  --account-name tfstatetodoapp \
                  --container-name plans \
                  --name ${{ parameters.environment }}/tfplan-${{ parameters.environment }}-$(Build.BuildId) \
                  --file "$PLAN_FILE" \
                  --overwrite true \
                  --auth-mode login

          - task: AzureCLI@2
            displayName: Download Terraform plan
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                mkdir -p $(Pipeline.Workspace)/tfplan/${{ parameters.environment }}

                az storage blob download \
                  --account-name tfstatetodoapp \
                  --container-name plans \
                  --name ${{ parameters.environment }}/tfplan-${{ parameters.environment }}-$(Build.BuildId) \
                  --file $(Pipeline.Workspace)/tfplan/${{ parameters.environment }}/tfplan-${{ parameters.environment }}-$(Build.BuildId) \
                  --auth-mode login

          - task: AzureCLI@2
            displayName: Apply Terraform
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                terraform init -reconfigure \
                  -backend-config=environments/${{ parameters.environment }}/${{ parameters.environment }}.tfbackend

                PLAN_FILE="$(Pipeline.Workspace)/tfplan/${{ parameters.environment }}/tfplan-${{ parameters.environment }}-$(Build.BuildId)"

                if [ ! -f "$PLAN_FILE" ]; then
                  echo "Terraform plan file not found!"
                  exit 1
                fi

                START_TIME=$(date +%s)

                terraform apply -auto-approve "$PLAN_FILE"

                END_TIME=$(date +%s)
                DURATION=$((END_TIME - START_TIME))

                MINUTES=$((DURATION / 60))
                SECONDS=$((DURATION % 60))

                echo "##[section]Terraform apply completed in ${MINUTES}m ${SECONDS}s"
              workingDirectory: $(System.DefaultWorkingDirectory)/infra
            env:
              ARM_SUBSCRIPTION_ID: $(subscription_id)

      - job: GetSWADeploymentToken
        displayName: Get SWA Deployment Token
        dependsOn: UploadPlanAndTerraformApply
        steps:
          - task: AzureCLI@2
            name: GetToken
            displayName: Get SWA Deployment Token
            inputs:
              azureSubscription: "todo-app-service-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list \
                  --name todo-app-${{ parameters.environment }}-frontend-static \
                  --resource-group rg-todo-app-${{ parameters.environment }} \
                  --query "properties.apiKey" \
                  -o tsv)

                echo "##vso[task.setvariable variable=SWA_DEPLOYMENT_TOKEN;isOutput=true;issecret=true]$SWA_DEPLOYMENT_TOKEN"
            env:
              ARM_SUBSCRIPTION_ID: $(subscription_id)

      - job: DeployFrontend
        displayName: Deploy Frontend to Azure Static Web Apps
        dependsOn: GetSWADeploymentToken
        variables:
          SWA_DEPLOYMENT_TOKEN: $[ dependencies.GetSWADeploymentToken.outputs['GetToken.SWA_DEPLOYMENT_TOKEN'] ]
        steps:
          - checkout: self

          - download: current
            artifact: frontend-dist

          - script: |
              echo "Pipeline.Workspace = $(Pipeline.Workspace)"
              echo "Contents of workspace:"
              find "$(Pipeline.Workspace)" -maxdepth 3 -type f | sort
            displayName: Show Artifact Contents

          - script: |
              rm -rf "$(System.DefaultWorkingDirectory)/frontend-dist"
              mkdir -p "$(System.DefaultWorkingDirectory)/frontend-dist"
              cp -R "$(Pipeline.Workspace)/frontend-dist/." \
                    "$(System.DefaultWorkingDirectory)/frontend-dist/"

              echo "Copied files:"
              find "$(System.DefaultWorkingDirectory)/frontend-dist" -maxdepth 3 -type f | sort
            displayName: Copy Artifact to Working Directory

          - task: AzureStaticWebApp@0
            displayName: Deploy to Azure Static Web Apps
            inputs:
              azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)
              app_location: "frontend-dist"
              output_location: ""
              skip_app_build: true
